Partially revert #52 in upstream
PR #52 in upstream forces gzip in http requests. In our case this causes
the following issue when parsing any site:

(1)(+0000843): Error: invalid distance too far back

    Error: invalid distance too far back
        at Zlib.zlibOnError [as onerror] (zlib.js:153:17)

  InternalServerError: An error occurred retrieving the document
      at Object.throw
(/root/srv/translation-server/node_modules/koa/lib/context.js:93:11)
      at module.exports.WebSession.handleURL
(/root/srv/translation-server/src/webSession.js:174:19)

This ends up being a product of the version of zlib1g on Debian Stretch
and nodejs 10.4.0~dfsg-1+wmf2. zlib1g on Debian Buster (not yet released
is fine). The root cause of the issue is not yet known. For now,
partially revert that PR removing the gzip option to restore
functionality

Change-Id: I7c7ecf53af5b375d76ba6a7af780b2ab7bd9b8ec